
package com.tutorial.webserviceClient.soap.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Math", targetNamespace = "http://soap.webservice.tutorial.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Math {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateRectangle", targetNamespace = "http://soap.webservice.tutorial.com/", className = "com.tutorial.webserviceClient.soap.stub.CalculateRectangle")
    @ResponseWrapper(localName = "calculateRectangleResponse", targetNamespace = "http://soap.webservice.tutorial.com/", className = "com.tutorial.webserviceClient.soap.stub.CalculateRectangleResponse")
    @Action(input = "http://soap.webservice.tutorial.com/Math/calculateRectangleRequest", output = "http://soap.webservice.tutorial.com/Math/calculateRectangleResponse")
    public int calculateRectangle(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateSquare", targetNamespace = "http://soap.webservice.tutorial.com/", className = "com.tutorial.webserviceClient.soap.stub.CalculateSquare")
    @ResponseWrapper(localName = "calculateSquareResponse", targetNamespace = "http://soap.webservice.tutorial.com/", className = "com.tutorial.webserviceClient.soap.stub.CalculateSquareResponse")
    @Action(input = "http://soap.webservice.tutorial.com/Math/calculateSquareRequest", output = "http://soap.webservice.tutorial.com/Math/calculateSquareResponse")
    public int calculateSquare(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
